# .github/workflows/sql-workflow.yml
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/sql-action@v1.3
      with:        
        connection-string: ${{ secrets.SQL_CONN_STRING_DEV }}
        dacpac-package: './AppTemplateDb.dacpac'
